"""updated total_time_in_foreground to int

Revision ID: 461b1826b95c
Revises: 631ffc7f0d6a
Create Date: 2025-04-06 18:22:42.999394

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '461b1826b95c'
down_revision = '631ffc7f0d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.alter_column('total_time_in_foreground',
               existing_type=mysql.DATETIME(),
               type_=sa.Integer(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.alter_column('total_time_in_foreground',
               existing_type=sa.Integer(),
               type_=mysql.DATETIME(),
               existing_nullable=True)

    # ### end Alembic commands ###
