"""updated app version feild size to 255

Revision ID: 631ffc7f0d6a
Revises: ad79cb49efbe
Create Date: 2025-04-06 18:19:05.505380

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '631ffc7f0d6a'
down_revision = 'ad79cb49efbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.alter_column('app_version',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.alter_column('app_version',
               existing_type=sa.String(length=255),
               type_=mysql.VARCHAR(length=50),
               existing_nullable=True)

    # ### end Alembic commands ###
