"""added missing tables

Revision ID: 882764890ee2
Revises: 425ab51a5390
Create Date: 2025-04-05 19:02:15.613235

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '882764890ee2'
down_revision = '425ab51a5390'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('ix_users_email')
        batch_op.drop_index('ix_users_fullname')
        batch_op.drop_index('ix_users_id')

    op.drop_table('users')
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.drop_index('ix_admins_email')
        batch_op.drop_index('ix_admins_fullname')
        batch_op.drop_index('ix_admins_id')

    op.drop_table('admins')
    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_name', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('version_code', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('install_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('last_update_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.drop_column('last_used')
        batch_op.drop_column('timestamp')
        batch_op.drop_column('is_enabled')
        batch_op.drop_column('total_time_in_foreground')

    with op.batch_alter_table('device_locations', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.BIGINT(),
               type_=sa.DateTime(),
               nullable=False)

    with op.batch_alter_table('keystrokes', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=mysql.BIGINT(),
               type_=sa.DateTime(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('keystrokes', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('device_locations', schema=None) as batch_op:
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=mysql.BIGINT(),
               nullable=True)

    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('total_time_in_foreground', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('is_enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timestamp', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('last_used', mysql.BIGINT(), autoincrement=False, nullable=True))
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_update_time')
        batch_op.drop_column('install_time')
        batch_op.drop_column('version_code')
        batch_op.drop_column('version_name')

    op.create_table('admins',
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fullname', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('admins', schema=None) as batch_op:
        batch_op.create_index('ix_admins_id', ['id'], unique=False)
        batch_op.create_index('ix_admins_fullname', ['fullname'], unique=False)
        batch_op.create_index('ix_admins_email', ['email'], unique=True)

    op.create_table('users',
    sa.Column('id', mysql.VARCHAR(length=40), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=120), nullable=True),
    sa.Column('fullname', mysql.VARCHAR(length=80), nullable=True),
    sa.Column('password', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('(now())'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index('ix_users_id', ['id'], unique=False)
        batch_op.create_index('ix_users_fullname', ['fullname'], unique=False)
        batch_op.create_index('ix_users_email', ['email'], unique=True)

    # ### end Alembic commands ###
