"""Updated App Info table

Revision ID: ad79cb49efbe
Revises: e0572bad1bc8
Create Date: 2025-04-06 18:14:43.097311

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ad79cb49efbe'
down_revision = 'e0572bad1bc8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('app_version', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('is_enabled', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('last_used_time', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('total_time_in_foreground', sa.DateTime(), nullable=True))
        batch_op.drop_column('version_code')
        batch_op.drop_column('last_update_time')
        batch_op.drop_column('version_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('apps_info', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version_name', mysql.VARCHAR(length=50), nullable=True))
        batch_op.add_column(sa.Column('last_update_time', mysql.DATETIME(), nullable=True))
        batch_op.add_column(sa.Column('version_code', mysql.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_column('total_time_in_foreground')
        batch_op.drop_column('last_used_time')
        batch_op.drop_column('is_enabled')
        batch_op.drop_column('app_version')

    # ### end Alembic commands ###
